# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: ['push', 'pull_request']

jobs:
  build:
    # playwright requires 22.04 for node 18.x and 20.x (playwirght 1.39.0)
    # for 24.04, playwright 1.59.0 is required
    # https://github.com/microsoft/playwright/issues/30368#issuecomment-2669259798
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npx playwright install
      - run: npm run test
